##
# Hermes 主题配置
# 参考 themes/hermes/_config.yml，可通过 _config.hermes.yml 进行站点级覆盖
##

# Comment system
disqus:

# Analytics
ga: G-WJ1ZY9QR8J

# Copyright Information
startyear: 2015

# Image Credits
enable_image_credit: false

logo: /images/fav/favicon.png
# 网站图标
favicon: /images/fav/favicon-48x48.png

# 用户头像与昵称
avatar:
  author_photo: /images/favicon.png
  author_nickname: Vastiny
  path: /

# 页脚信息
footer:
  - name: Copyright © Vastiny 2026 :P
    path: https://vastiny.com
  - name: Theme by Leedom | Powered by Hexo
    path: https://github.com/leedom92/hexo-theme-leedom

# 顶部菜单
menu:
  GitHub: https://github.com/yantze
  Twitter: https://twitter.com/ivastiny
  Feed: atom.xml
