##
# Hermes 主题配置
# 参考 themes/hermes/_config.yml，可通过 _config.hermes.yml 进行站点级覆盖
##

# Comment system
disqus:

# Analytics
ga: G-WJ1ZY9QR8J

# Copyright Information
startyear: 2018

# Image Credits
enable_image_credit: true

# Logo 与导航图标
logo: /images/favicon.png

# 网站图标
favicon:
  enable: true
  icon: /images/custom-icon.png
  ico: /images/custom-icon.ico
  touch_icon: /images/custom-icon-touch.png

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.png
  author_nickname: Vastiny
  path: /

# 页脚信息
footer:
  - name: Copyright © Vastiny 2026 :P
    path: https://vastiny.com
  - name: Theme by Leedom | Powered by Hexo
    path: https://github.com/leedom92/hexo-theme-leedom

# 顶部菜单
menu:
  GitHub: https://github.com/yantze
  Twitter: https://twitter.com/ivastiny
  Feed: atom.xml
